# Generated by Django 2.2.9 on 2022-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('MANAGER', 'MANAGER'), ('CLIENT', 'CLIENT')], default='MANAGER', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CqUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('AUDITOR', 'AUDITOR'), ('MANAGER', 'MANAGER'), ('QA', 'QA')], max_length=254)),
                ('specialties', models.ManyToManyField(related_name='specialties', to='CQapp.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='CqTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='CQapp.CqUser')),
            ],
        ),
    ]
